payment.not.configured=Chưa cấu hình mô-đun thanh toán

payment.type.MONEYORDER=Lệnh chuyển tiền / Séc
payment.type.PAYPAL=PayPal
payment.type.CREDITCARD=Thẻ tín dụng
payment.type.STRIPE=Thẻ tín dụng
payment.type.STRIPE3=Thẻ tín dụng
payment.type.BRAINTREE=Thẻ tín dụng

label.payment.moneyorder.usemoneyorder=Sử dụng lệnh chuyển tiền / séc

module.payment.paypal=PayPal
module.payment.beanstream=Beanstream
module.payment.authorizenet=Authorize Net
module.payment.moneyorder=Lệnh chuyển tiền / Séc
module.payment.paypal-express-checkout=PayPal Express Checkout
module.payment.stripe=Stripe
module.payment.stripe3=Stripe V3 (Hỗ trợ 3DSecure - yêu cầu Webhook)
module.payment.braintree=Braintree

module.payment.transactiontype=Loại giao dịch
module.payment.transactiontype.preauth=Xác thực trước (Pre-authorization)
module.payment.transactiontype.capture=Thu tiền (Capture)
module.payment.transactiontype.sale=Bán hàng trực tiếp (Sale)
module.payment.transactiontype.refund=Hoàn tiền (Refund)

#PayPal
module.payment.paypal-express-checkout.userid=Tên người dùng PayPal API
module.payment.paypal-express-checkout.apikey=Mật khẩu PayPal API
module.payment.paypal-express-checkout.signature=Chữ ký PayPal API
module.payment.paypal-express-checkout.applicationid=Mã ứng dụng PayPal (Application ID)
module.payment.paypal-express-checkout.note=Làm theo hướng dẫn tại đây để tạo Tên người dùng, Mật khẩu và Chữ ký PayPal API (https://developer.paypal.com/docs/classic/api/apiCredentials/#creating-classic-api-credentials)

#paypal rest
module,payment.paypal.clientId=PayPal Client ID
module,payment.paypal.secret=PayPal Secret Key
module.payment.paypal.note=Tạo một tài khoản bán hàng PayPal (www.paypal.com). Sau khi hoàn tất, đăng nhập vào trang Developer của PayPal (https://developer.paypal.com/webapps/developer/index) bằng thông tin tài khoản đó. Nhấp vào "Applications" trên thanh điều hướng để đến trang My Applications. Nhấp vào nút "Create App" để nhận Client ID và Secret Key.
module.payment.paypal.message.clientId=PayPal Client ID là bắt buộc
module.payment.paypal.message.secret=PayPal Secret Key là bắt buộc

module.payment.paypal.message.identifier=Yêu cầu nhập tên người dùng PayPal API
module.payment.paypal.message.api=Yêu cầu nhập tên người dùng PayPal API
module.payment.paypal.message.password=Yêu cầu nhập mật khẩu PayPal API
module.payment.paypal.message.signature=Yêu cầu nhập chữ ký PayPal API

#Beanstream
module.payment.beanstream.merchantid=Mã người bán (Merchant ID)
module.payment.beanstream.username=Tên đăng nhập
module.payment.beanstream.password=Mật khẩu

module.payment.beanstream.message.merchantid=Mã người bán là bắt buộc
module.payment.beanstream.message.username=Tên đăng nhập là bắt buộc
module.payment.beanstream.message.password=Mật khẩu là bắt buộc

#Moneyorder
module.payment.moneyorder.adress=Địa chỉ nhận séc / lệnh chuyển tiền
module.payment.moneyorder.message.address=Địa chỉ là bắt buộc