NO_SHIPPING_MODULE_CONFIGURED=Chưa cấu hình mô-đun vận chuyển

module.shipping.canadapost=Canada Post
module.shipping.ups=UPS
module.shipping.usps=Dịch vụ Bưu chính Hoa Kỳ (USPS)
module.shipping.fedex=Fedex
module.shipping.weightBased=Giá vận chuyển theo trọng lượng
module.shipping.customQuotesRules=Vận chuyển theo {0}
module.shipping.storePickUp=Nhận hàng tại cửa hàng
module.shipping.priceByDistance=Vận chuyển theo {0}

module.shipping.storePickUp.note=Tùy chọn này cho phép bạn giữ hàng trực tuyến và tự đến cửa hàng để nhận hàng. Tùy chọn này cũng xuất hiện khi khu vực của bạn không có đơn vị vận chuyển nào khác hỗ trợ.

#custom
module.shipping.customQuotesRules.title=Tạo quy tắc báo giá vận chuyển tùy chỉnh
module.shipping.customQuotesRules.text=Sử dụng hệ thống quy tắc để tạo bảng quyết định cước phí vận chuyển riêng. Bảng này có thể chỉnh sửa tại sm-core/src/main/resources/rules/shipping-custom-rules.xls 

#custom
module.shipping.priceByDistance.title=Tạo báo giá vận chuyển dựa trên khoảng cách
module.shipping.priceByDistance.text=Thực hiện cài đặt giá vận chuyển (theo km). Yêu cầu phải cài bộ tính khoảng cách tiền xử lý.

module.shipping.canada=Canada
module.shipping.usa=Mỹ (Hoa Kỳ)
module.shipping.international=Quốc tế

#Canada Post
module.shipping.canadapost.identifier=Mã định danh Canada Post (mã CPC)
module.shipping.canadapost.username=Tên đăng nhập Canada Post (phần đầu API key trước dấu chấm phẩy)
module.shipping.canadapost.password=Mật khẩu Canada Post (phần thứ hai API key sau dấu chấm phẩy)
module.shipping.canadapost.apikey=Khóa API Canada Post
module.shipping.canadapost.packages=Loại kiện hàng
module.shipping.canadapost.services=Các dịch vụ được áp dụng báo giá
module.shipping.canadapost.message.identifier=Yêu cầu mã định danh Canada Post
module.shipping.canadapost.message.username=Yêu cầu tên đăng nhập Canada Post
module.shipping.canadapost.message.password=Yêu cầu mật khẩu Canada Post
module.shipping.canadapost.message.apikey=Yêu cầu API key Canada Post

module.shipping.canadapost.DOM.RP=Bưu kiện Thường (Nội địa)
module.shipping.canadapost.DOM.EP=Bưu kiện Chuyển phát nhanh (Nội địa)
module.shipping.canadapost.DOM.XP=Xpresspost (Nội địa)
module.shipping.canadapost.DOM.XP.CERT=Xpresspost Bảo đảm (Nội địa)
module.shipping.canadapost.DOM.PC=Chuyển phát Ưu tiên (Nội địa)
module.shipping.canadapost.DOM.DT=Giao hàng trong đêm (Nội địa)
module.shipping.canadapost.DOM.LIB=Sách thư viện (Nội địa)

module.shipping.canadapost.USA.EP=Bưu kiện Chuyển phát nhanh sang Mỹ
module.shipping.canadapost.USA.PW.ENV=Bì thư Ưu tiên toàn cầu sang Mỹ
module.shipping.canadapost.USA.PW.PAK=Gói hàng Ưu tiên toàn cầu sang Mỹ
module.shipping.canadapost.USA.PW.PARCEL=Bưu kiện Ưu tiên toàn cầu sang Mỹ
module.shipping.canadapost.USA.SP.AIR=Gói hàng nhỏ Đường hàng không sang Mỹ
module.shipping.canadapost.USA.TP=Gói hàng có Định vị (Tracked Packet) - Mỹ
module.shipping.canadapost.USA.TP.LVM=Gói hàng có Định vị - Mỹ - (LVM - Dành cho người gửi số lượng lớn)
module.shipping.canadapost.USA.XP=Xpresspost sang Mỹ

module.shipping.canadapost.INT.XP=Xpresspost Quốc tế
module.shipping.canadapost.INT.IP.AIR=Bưu kiện Quốc tế Đường hàng không
module.shipping.canadapost.INT.IP.SURF=Bưu kiện Quốc tế Đường bộ/biển
module.shipping.canadapost.INT.PW.ENV=Bì thư Ưu tiên toàn cầu Quốc tế
module.shipping.canadapost.INT.PW.PAK=Gói hàng Ưu tiên toàn cầu Quốc tế
module.shipping.canadapost.INT.PW.PARCEL=Bưu kiện Ưu tiên toàn cầu Quốc tế
module.shipping.canadapost.INT.SP.AIR=Gói hàng nhỏ Quốc tế Đường hàng không
module.shipping.canadapost.INT.SP.SURF=Gói hàng nhỏ Quốc tế Đường bộ/biển
module.shipping.canadapost.INT.TP=Gói hàng có Định vị - Quốc tế

#USPS
module.shipping.usps.identifier=Mã tài khoản USPS
module.shipping.usps.packages=Loại kiện hàng
module.shipping.usps.shippingmethods=Chọn tối đa 3 phương thức vận chuyển
module.shipping.usps.message.identifier=Yêu cầu nhập mã tài khoản USPS
module.shipping.usps.message.packages=Bạn phải chọn ít nhất một loại kiện hàng

module.shipping.usps.package.01=Tùy chỉnh (Variable)
module.shipping.usps.package.02=Hộp giá cố định (Flat Rate Box)
module.shipping.usps.package.03=Bì thư giá cố định (Flat Rate Envelope)
module.shipping.usps.package.04=Hình hộp chữ nhật
module.shipping.usps.package.05=Không phải hình hộp chữ nhật
module.shipping.usps.package.06=Hộp giá cố định cỡ lớn (LG Flat Rate Box)

module.shipping.usps.package.07=Bì thư
module.shipping.usps.package.08=Kiện hàng

module.shipping.usps.method.01=Thư Hạng Nhất (First-Class Mail)
module.shipping.usps.method.02=Thư Ưu tiên (Priority Mail)
module.shipping.usps.method.03=Thư Hỏa tốc (Express Mail)
module.shipping.usps.method.04=Hỏa tốc giao tận tay (Express SH)
module.shipping.usps.method.05=Hỏa tốc nhận tại bưu cục (Express HFP)
module.shipping.usps.method.06=Bưu phẩm in ấn (BPM)
module.shipping.usps.method.07=Chuyển phát bưu kiện (Parcel Post)

#UPS
module.shipping.ups.identifier=Khóa truy cập UPS (Access key)
module.shipping.ups.userid=Tên đăng nhập (User ID)
module.shipping.ups.password=Mật khẩu
module.shipping.ups.packages=Loại kiện hàng
module.shipping.ups.shippingmethods=Chọn phương thức vận chuyển
module.shipping.ups.message.identifier=Yêu cầu mã tài khoản UPS
module.shipping.ups.message.packages=Bạn phải chọn một loại kiện hàng

module.shipping.ups.package.02=Kiện hàng của khách hàng
module.shipping.ups.packagel.01=Bì thư UPS (UPS Letter)
module.shipping.ups.package.03=Ống cuộn UPS (UPS Tube)
module.shipping.ups.package.04=Gói hàng UPS (UPS Pak)
module.shipping.ups.package.21=Hộp chuyển phát nhanh UPS (UPS Express Box)
module.shipping.ups.package.24=Hộp UPS 25kg
module.shipping.ups.package.10=Hộp UPS 10kg
module.shipping.ups.package.25=Không xác định

module.shipping.ups.method.01=UPS Chuyển phát hỏa tốc ngày hôm sau (Next Day Air)
module.shipping.ups.method.02=UPS Chuyển phát 2 ngày (Second Day Air)
module.shipping.ups.method.03=UPS Giao hàng đường bộ (Ground)
module.shipping.ups.method.07=UPS Hỏa tốc toàn cầu (Worldwide Express)
module.shipping.ups.method.08=UPS Chuyển phát nhanh toàn cầu (Worldwide Expedited)
module.shipping.ups.method.11=UPS Tiêu chuẩn (Standard)
module.shipping.ups.method.12=UPS Giao 3 ngày (Three-Day Select)
module.shipping.ups.method.13=UPS Tiết kiệm Hỏa tốc ngày hôm sau (Next Day Air Saver)
module.shipping.ups.method.14=UPS Hỏa tốc sáng sớm ngày hôm sau (Next Day Air Early A.M.)
module.shipping.ups.method.54=UPS Hỏa tốc cao cấp toàn cầu (Worldwide Express Plus)
module.shipping.ups.method.59=UPS Chuyển phát 2 ngày buổi sáng (Second Day Air A.M.)
module.shipping.ups.method.65=UPS Tiết kiệm (Saver)

module.shipping.ups.method=Các phương thức vận chuyển của UPS
module.shipping.ups.method.select=Chọn một phương thức vận chuyển cụ thể của UPS
module.shipping.ups.method.unselect=Để UPS tự đề xuất tất cả các phương thức khả thi

#store pick up
module.shipping.storePickUp.address=Địa chỉ lấy hàng sẽ hiển thị cho khách hàng
module.shipping.storePickUp.address.message=Địa chỉ lấy hàng là trường dữ liệu bắt buộc
module.shipping.storePickUp.price=Phí nhận tại cửa hàng dạng số (thường là 0)
module.shipping.storePickUp.price.message=Phí nhận tại cửa hàng là bắt buộc (ở định dạng số)