-- Bảng mapping từ tên region của IP2Location sang Mã Tỉnh Thành GSO Việt Nam (63 tỉnh/thành)
-- Bao gồm cả biến thể tiếng Anh / Không dấu thường gặp trong CSDL IP2Location

CREATE TABLE IF NOT EXISTS `ip2location_gso_province_mapping` (
  `ip2location_region` VARCHAR(100) NOT NULL,
  `gso_province_id` VARCHAR(10) NOT NULL,
  `gso_province_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ip2location_region`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `ip2location_gso_province_mapping` (`ip2location_region`, `gso_province_id`, `gso_province_name`) VALUES
('An Giang', '89', 'An Giang'),
('Ba Ria - Vung Tau', '77', 'Bà Rịa - Vũng Tàu'),
('Vung Tau', '77', 'Bà Rịa - Vũng Tàu'),
('Bac Giang', '24', 'Bắc Giang'),
('Bac Kan', '06', 'Bắc Kạn'),
('Bac Lieu', '95', 'Bạc Liêu'),
('Bac Ninh', '27', 'Bắc Ninh'),
('Ben Tre', '83', 'Bến Tre'),
('Binh Dinh', '52', 'Bình Định'),
('Binh Duong', '74', 'Bình Dương'),
('Binh Phuoc', '70', 'Bình Phước'),
('Binh Thuan', '60', 'Bình Thuận'),
('Ca Mau', '96', 'Cà Mau'),
('Can Tho', '92', 'Cần Thơ'),
('Cao Bang', '04', 'Cao Bằng'),
('Da Nang', '48', 'Đà Nẵng'),
('Dak Lak', '66', 'Đắk Lắk'),
('Dac Lac', '66', 'Đắk Lắk'),
('Dak Nong', '67', 'Đắk Nông'),
('Dac Nong', '67', 'Đắk Nông'),
('Dien Bien', '11', 'Điện Biên'),
('Dong Nai', '75', 'Đồng Nai'),
('Dong Thap', '87', 'Đồng Tháp'),
('Gia Lai', '64', 'Gia Lai'),
('Ha Giang', '02', 'Hà Giang'),
('Ha Nam', '35', 'Hà Nam'),
('Ha Noi', '01', 'Hà Nội'),
('Hanoi', '01', 'Hà Nội'),
('Ha Tinh', '42', 'Hà Tĩnh'),
('Hai Duong', '30', 'Hải Dương'),
('Hai Phong', '31', 'Hải Phòng'),
('Hau Giang', '93', 'Hậu Giang'),
('Ho Chi Minh', '79', 'Hồ Chí Minh'),
('Ho Chi Minh City', '79', 'Hồ Chí Minh'),
('Hoa Binh', '17', 'Hòa Bình'),
('Hung Yen', '33', 'Hưng Yên'),
('Khanh Hoa', '56', 'Khánh Hòa'),
('Kien Giang', '91', 'Kiên Giang'),
('Kon Tum', '62', 'Kon Tum'),
('Lai Chau', '12', 'Lai Châu'),
('Lam Dong', '68', 'Lâm Đồng'),
('Lang Son', '20', 'Lạng Sơn'),
('Lao Cai', '14', 'Lào Cai'),
('Long An', '80', 'Long An'),
('Nam Dinh', '36', 'Nam Định'),
('Nghe An', '40', 'Nghệ An'),
('Ninh Binh', '37', 'Ninh Bình'),
('Ninh Thuan', '58', 'Ninh Thuận'),
('Phu Tho', '25', 'Phú Thọ'),
('Phu Yen', '54', 'Phú Yên'),
('Quang Binh', '44', 'Quảng Bình'),
('Quang Nam', '49', 'Quảng Nam'),
('Quang Ngai', '51', 'Quảng Ngãi'),
('Quang Ninh', '22', 'Quảng Ninh'),
('Quang Tri', '45', 'Quảng Trị'),
('Soc Trang', '94', 'Sóc Trăng'),
('Son La', '14', 'Sơn La'),
('Tay Ninh', '72', 'Tây Ninh'),
('Thai Binh', '34', 'Thái Bình'),
('Thai Nguyen', '19', 'Thái Nguyên'),
('Thanh Hoa', '38', 'Thanh Hóa'),
('Thua Thien Hue', '46', 'Thừa Thiên Huế'),
('Thua Thien-Hue', '46', 'Thừa Thiên Huế'),
('Hue', '46', 'Thừa Thiên Huế'),
('Tien Giang', '82', 'Tiền Giang'),
('Tra Vinh', '84', 'Trà Vinh'),
('Tuyen Quang', '08', 'Tuyên Quang'),
('Vinh Long', '86', 'Vĩnh Long'),
('Vinh Phuc', '26', 'Vĩnh Phúc'),
('Yen Bai', '15', 'Yên Bái');